# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/_actionPredictor.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyQtKinectDemo(object):
    def setupUi(self, PyQtKinectDemo):
        PyQtKinectDemo.setObjectName("PyQtKinectDemo")
        PyQtKinectDemo.resize(1632, 990)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PyQtKinectDemo.sizePolicy().hasHeightForWidth())
        PyQtKinectDemo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        PyQtKinectDemo.setFont(font)
        PyQtKinectDemo.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(PyQtKinectDemo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_9.setContentsMargins(11, 0, 11, 0)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.organizationFrame = QtWidgets.QFrame(self.centralWidget)
        self.organizationFrame.setObjectName("organizationFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.organizationFrame)
        self.horizontalLayout_4.setContentsMargins(18, 0, 18, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uniLogoLabel = QtWidgets.QLabel(self.organizationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uniLogoLabel.sizePolicy().hasHeightForWidth())
        self.uniLogoLabel.setSizePolicy(sizePolicy)
        self.uniLogoLabel.setMinimumSize(QtCore.QSize(0, 97))
        self.uniLogoLabel.setMaximumSize(QtCore.QSize(16777215, 97))
        self.uniLogoLabel.setObjectName("uniLogoLabel")
        self.horizontalLayout_4.addWidget(self.uniLogoLabel)
        self.facultySchoolFrame = QtWidgets.QFrame(self.organizationFrame)
        self.facultySchoolFrame.setObjectName("facultySchoolFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.facultySchoolFrame)
        self.verticalLayout_4.setContentsMargins(11, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.facultyLabel = QtWidgets.QLabel(self.facultySchoolFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.facultyLabel.setFont(font)
        self.facultyLabel.setObjectName("facultyLabel")
        self.verticalLayout_4.addWidget(self.facultyLabel)
        self.schoolLabel = QtWidgets.QLabel(self.facultySchoolFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.schoolLabel.setFont(font)
        self.schoolLabel.setObjectName("schoolLabel")
        self.verticalLayout_4.addWidget(self.schoolLabel)
        self.horizontalLayout_4.addWidget(self.facultySchoolFrame)
        self.verticalFrame = QtWidgets.QFrame(self.organizationFrame)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.appTitleLabel = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.appTitleLabel.setFont(font)
        self.appTitleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.appTitleLabel.setObjectName("appTitleLabel")
        self.verticalLayout_7.addWidget(self.appTitleLabel)
        self.label = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.horizontalLayout_4.addWidget(self.verticalFrame)
        self.verticalLayout_9.addWidget(self.organizationFrame)
        self.streamFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.streamFrame.sizePolicy().hasHeightForWidth())
        self.streamFrame.setSizePolicy(sizePolicy)
        self.streamFrame.setMinimumSize(QtCore.QSize(642, 242))
        self.streamFrame.setStyleSheet("")
        self.streamFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.streamFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.streamFrame.setObjectName("streamFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.streamFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rgbWidget = QtWidgets.QWidget(self.streamFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbWidget.sizePolicy().hasHeightForWidth())
        self.rgbWidget.setSizePolicy(sizePolicy)
        self.rgbWidget.setObjectName("rgbWidget")
        self.verticalTopLayout = QtWidgets.QVBoxLayout(self.rgbWidget)
        self.verticalTopLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalTopLayout.setSpacing(6)
        self.verticalTopLayout.setObjectName("verticalTopLayout")
        self.rgbTitle = QtWidgets.QLabel(self.rgbWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbTitle.sizePolicy().hasHeightForWidth())
        self.rgbTitle.setSizePolicy(sizePolicy)
        self.rgbTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.rgbTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.rgbTitle.setFont(font)
        self.rgbTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbTitle.setObjectName("rgbTitle")
        self.verticalTopLayout.addWidget(self.rgbTitle)
        self.rgbLabel = QtWidgets.QLabel(self.rgbWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbLabel.sizePolicy().hasHeightForWidth())
        self.rgbLabel.setSizePolicy(sizePolicy)
        self.rgbLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.rgbLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.rgbLabel.setFont(font)
        self.rgbLabel.setAutoFillBackground(False)
        self.rgbLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.rgbLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rgbLabel.setScaledContents(True)
        self.rgbLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbLabel.setObjectName("rgbLabel")
        self.verticalTopLayout.addWidget(self.rgbLabel)
        self.horizontalLayout.addWidget(self.rgbWidget)
        self.depthWidget = QtWidgets.QWidget(self.streamFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthWidget.sizePolicy().hasHeightForWidth())
        self.depthWidget.setSizePolicy(sizePolicy)
        self.depthWidget.setObjectName("depthWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.depthWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.depthTitle = QtWidgets.QLabel(self.depthWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthTitle.sizePolicy().hasHeightForWidth())
        self.depthTitle.setSizePolicy(sizePolicy)
        self.depthTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.depthTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.depthTitle.setFont(font)
        self.depthTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.depthTitle.setObjectName("depthTitle")
        self.verticalLayout_5.addWidget(self.depthTitle)
        self.depthLabel = QtWidgets.QLabel(self.depthWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthLabel.sizePolicy().hasHeightForWidth())
        self.depthLabel.setSizePolicy(sizePolicy)
        self.depthLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.depthLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.depthLabel.setFont(font)
        self.depthLabel.setAutoFillBackground(False)
        self.depthLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.depthLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.depthLabel.setScaledContents(True)
        self.depthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.depthLabel.setObjectName("depthLabel")
        self.verticalLayout_5.addWidget(self.depthLabel)
        self.horizontalLayout.addWidget(self.depthWidget)
        self.verticalWidget = QtWidgets.QWidget(self.streamFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.actionListTitleLabel = QtWidgets.QLabel(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionListTitleLabel.sizePolicy().hasHeightForWidth())
        self.actionListTitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.actionListTitleLabel.setFont(font)
        self.actionListTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionListTitleLabel.setObjectName("actionListTitleLabel")
        self.verticalLayout.addWidget(self.actionListTitleLabel)
        self.actionListWidget = QtWidgets.QListWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionListWidget.sizePolicy().hasHeightForWidth())
        self.actionListWidget.setSizePolicy(sizePolicy)
        self.actionListWidget.setMinimumSize(QtCore.QSize(320, 480))
        self.actionListWidget.setMaximumSize(QtCore.QSize(320, 480))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.actionListWidget.setFont(font)
        self.actionListWidget.setObjectName("actionListWidget")
        self.verticalLayout.addWidget(self.actionListWidget)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.verticalLayout_9.addWidget(self.streamFrame)
        self.predictResultFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictResultFrame.sizePolicy().hasHeightForWidth())
        self.predictResultFrame.setSizePolicy(sizePolicy)
        self.predictResultFrame.setStyleSheet("")
        self.predictResultFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.predictResultFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.predictResultFrame.setObjectName("predictResultFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.predictResultFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridFrame = QtWidgets.QFrame(self.predictResultFrame)
        self.gridFrame.setObjectName("gridFrame")
        self.predictionGridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.predictionGridLayout.setContentsMargins(11, 11, 11, 11)
        self.predictionGridLayout.setSpacing(6)
        self.predictionGridLayout.setObjectName("predictionGridLayout")
        self.actionClassTitleLabel = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.actionClassTitleLabel.setFont(font)
        self.actionClassTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionClassTitleLabel.setObjectName("actionClassTitleLabel")
        self.predictionGridLayout.addWidget(self.actionClassTitleLabel, 1, 0, 1, 1)
        self.actionClassTitleLabel2 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.actionClassTitleLabel2.setFont(font)
        self.actionClassTitleLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.actionClassTitleLabel2.setObjectName("actionClassTitleLabel2")
        self.predictionGridLayout.addWidget(self.actionClassTitleLabel2, 1, 1, 1, 1)
        self.actionEndTitleLabel = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionEndTitleLabel.sizePolicy().hasHeightForWidth())
        self.actionEndTitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.actionEndTitleLabel.setFont(font)
        self.actionEndTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionEndTitleLabel.setObjectName("actionEndTitleLabel")
        self.predictionGridLayout.addWidget(self.actionEndTitleLabel, 1, 4, 1, 1)
        self.actionStartTitleLabel = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionStartTitleLabel.sizePolicy().hasHeightForWidth())
        self.actionStartTitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.actionStartTitleLabel.setFont(font)
        self.actionStartTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionStartTitleLabel.setObjectName("actionStartTitleLabel")
        self.predictionGridLayout.addWidget(self.actionStartTitleLabel, 1, 3, 1, 1)
        self.eventTitleLabel = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.eventTitleLabel.setFont(font)
        self.eventTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.eventTitleLabel.setObjectName("eventTitleLabel")
        self.predictionGridLayout.addWidget(self.eventTitleLabel, 1, 2, 1, 1)
        self.actionClassNameLabel = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setUnderline(True)
        self.actionClassNameLabel.setFont(font)
        self.actionClassNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionClassNameLabel.setObjectName("actionClassNameLabel")
        self.predictionGridLayout.addWidget(self.actionClassNameLabel, 0, 0, 1, 1)
        self.actionClassConfidenceLabel = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setUnderline(True)
        self.actionClassConfidenceLabel.setFont(font)
        self.actionClassConfidenceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionClassConfidenceLabel.setObjectName("actionClassConfidenceLabel")
        self.predictionGridLayout.addWidget(self.actionClassConfidenceLabel, 0, 1, 1, 1)
        self.eventPredictLabel = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setUnderline(True)
        self.eventPredictLabel.setFont(font)
        self.eventPredictLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.eventPredictLabel.setObjectName("eventPredictLabel")
        self.predictionGridLayout.addWidget(self.eventPredictLabel, 0, 2, 1, 1)
        self.actionStartConfidenceLabel = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionStartConfidenceLabel.sizePolicy().hasHeightForWidth())
        self.actionStartConfidenceLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setUnderline(True)
        self.actionStartConfidenceLabel.setFont(font)
        self.actionStartConfidenceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionStartConfidenceLabel.setObjectName("actionStartConfidenceLabel")
        self.predictionGridLayout.addWidget(self.actionStartConfidenceLabel, 0, 3, 1, 1)
        self.actionEndConfidenceLabel = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionEndConfidenceLabel.sizePolicy().hasHeightForWidth())
        self.actionEndConfidenceLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setUnderline(True)
        self.actionEndConfidenceLabel.setFont(font)
        self.actionEndConfidenceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionEndConfidenceLabel.setObjectName("actionEndConfidenceLabel")
        self.predictionGridLayout.addWidget(self.actionEndConfidenceLabel, 0, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.gridFrame)
        self.verticalLayout_9.addWidget(self.predictResultFrame)
        self.instructionLabel = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setWordWrap(True)
        self.instructionLabel.setObjectName("instructionLabel")
        self.verticalLayout_9.addWidget(self.instructionLabel)
        self.horizontalFrame = QtWidgets.QFrame(self.centralWidget)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.predictSettingFrame = QtWidgets.QFrame(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictSettingFrame.sizePolicy().hasHeightForWidth())
        self.predictSettingFrame.setSizePolicy(sizePolicy)
        self.predictSettingFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.predictSettingFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.predictSettingFrame.setObjectName("predictSettingFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.predictSettingFrame)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.predictSettingTitleLabel = QtWidgets.QLabel(self.predictSettingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictSettingTitleLabel.sizePolicy().hasHeightForWidth())
        self.predictSettingTitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.predictSettingTitleLabel.setFont(font)
        self.predictSettingTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.predictSettingTitleLabel.setObjectName("predictSettingTitleLabel")
        self.verticalLayout_2.addWidget(self.predictSettingTitleLabel)
        self.predictSettingWidget = QtWidgets.QWidget(self.predictSettingFrame)
        self.predictSettingWidget.setObjectName("predictSettingWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.predictSettingWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.recordingFrame = QtWidgets.QFrame(self.predictSettingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordingFrame.sizePolicy().hasHeightForWidth())
        self.recordingFrame.setSizePolicy(sizePolicy)
        self.recordingFrame.setObjectName("recordingFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.recordingFrame)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.datasetComboBox = QtWidgets.QComboBox(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.datasetComboBox.setFont(font)
        self.datasetComboBox.setObjectName("datasetComboBox")
        self.datasetComboBox.addItem("")
        self.datasetComboBox.addItem("")
        self.datasetComboBox.addItem("")
        self.gridLayout.addWidget(self.datasetComboBox, 2, 0, 1, 1)
        self.stopPredictButton = QtWidgets.QPushButton(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.stopPredictButton.setFont(font)
        self.stopPredictButton.setObjectName("stopPredictButton")
        self.gridLayout.addWidget(self.stopPredictButton, 3, 1, 1, 1)
        self.startPredictButton = QtWidgets.QPushButton(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.startPredictButton.setFont(font)
        self.startPredictButton.setObjectName("startPredictButton")
        self.gridLayout.addWidget(self.startPredictButton, 2, 1, 1, 1)
        self.interactCheckBox = QtWidgets.QCheckBox(self.recordingFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.interactCheckBox.setFont(font)
        self.interactCheckBox.setCheckable(True)
        self.interactCheckBox.setObjectName("interactCheckBox")
        self.gridLayout.addWidget(self.interactCheckBox, 3, 0, 1, 1)
        self.datasetLabel = QtWidgets.QLabel(self.recordingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetLabel.sizePolicy().hasHeightForWidth())
        self.datasetLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.datasetLabel.setFont(font)
        self.datasetLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.datasetLabel.setObjectName("datasetLabel")
        self.gridLayout.addWidget(self.datasetLabel, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.recordingFrame)
        self.frameRateGridWidget = QtWidgets.QWidget(self.predictSettingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRateGridWidget.sizePolicy().hasHeightForWidth())
        self.frameRateGridWidget.setSizePolicy(sizePolicy)
        self.frameRateGridWidget.setObjectName("frameRateGridWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameRateGridWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameRateSlider = QtWidgets.QSlider(self.frameRateGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRateSlider.sizePolicy().hasHeightForWidth())
        self.frameRateSlider.setSizePolicy(sizePolicy)
        self.frameRateSlider.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frameRateSlider.setMinimum(0)
        self.frameRateSlider.setMaximum(200)
        self.frameRateSlider.setSingleStep(1)
        self.frameRateSlider.setProperty("value", 200)
        self.frameRateSlider.setSliderPosition(200)
        self.frameRateSlider.setOrientation(QtCore.Qt.Vertical)
        self.frameRateSlider.setObjectName("frameRateSlider")
        self.gridLayout_3.addWidget(self.frameRateSlider, 1, 1, 1, 1)
        self.frameRateLabel = QtWidgets.QLabel(self.frameRateGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRateLabel.sizePolicy().hasHeightForWidth())
        self.frameRateLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frameRateLabel.setFont(font)
        self.frameRateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frameRateLabel.setObjectName("frameRateLabel")
        self.gridLayout_3.addWidget(self.frameRateLabel, 0, 0, 1, 1)
        self.frameRateValueLabel = QtWidgets.QLabel(self.frameRateGridWidget)
        self.frameRateValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frameRateValueLabel.setObjectName("frameRateValueLabel")
        self.gridLayout_3.addWidget(self.frameRateValueLabel, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameRateGridWidget)
        self.verticalLayout_2.addWidget(self.predictSettingWidget)
        self.horizontalLayout_3.addWidget(self.predictSettingFrame)
        self.middleButtonFrame = QtWidgets.QFrame(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleButtonFrame.sizePolicy().hasHeightForWidth())
        self.middleButtonFrame.setSizePolicy(sizePolicy)
        self.middleButtonFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.middleButtonFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.middleButtonFrame.setObjectName("middleButtonFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.middleButtonFrame)
        self.verticalLayout_6.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sensorControlLabel = QtWidgets.QLabel(self.middleButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorControlLabel.sizePolicy().hasHeightForWidth())
        self.sensorControlLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.sensorControlLabel.setFont(font)
        self.sensorControlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sensorControlLabel.setObjectName("sensorControlLabel")
        self.verticalLayout_6.addWidget(self.sensorControlLabel)
        self.sensorControlFrame = QtWidgets.QFrame(self.middleButtonFrame)
        self.sensorControlFrame.setObjectName("sensorControlFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sensorControlFrame)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resumeButton = QtWidgets.QPushButton(self.sensorControlFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.resumeButton.setFont(font)
        self.resumeButton.setObjectName("resumeButton")
        self.gridLayout_2.addWidget(self.resumeButton, 1, 0, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.sensorControlFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pauseButton.setFont(font)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout_2.addWidget(self.pauseButton, 0, 0, 1, 1)
        self.tiltUpButton = QtWidgets.QPushButton(self.sensorControlFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tiltUpButton.setFont(font)
        self.tiltUpButton.setObjectName("tiltUpButton")
        self.gridLayout_2.addWidget(self.tiltUpButton, 0, 1, 1, 1)
        self.tiltDownButton = QtWidgets.QPushButton(self.sensorControlFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tiltDownButton.setFont(font)
        self.tiltDownButton.setObjectName("tiltDownButton")
        self.gridLayout_2.addWidget(self.tiltDownButton, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.sensorControlFrame)
        self.resetButton = QtWidgets.QPushButton(self.middleButtonFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_6.addWidget(self.resetButton)
        self.horizontalLayout_3.addWidget(self.middleButtonFrame)
        self.verticalLayout_9.addWidget(self.horizontalFrame)
        PyQtKinectDemo.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(PyQtKinectDemo)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1632, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        PyQtKinectDemo.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(PyQtKinectDemo)
        self.statusBar.setObjectName("statusBar")
        PyQtKinectDemo.setStatusBar(self.statusBar)
        self.actionSettings = QtWidgets.QAction(PyQtKinectDemo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.actionSettings.setFont(font)
        self.actionSettings.setObjectName("actionSettings")
        self.actionInformation = QtWidgets.QAction(PyQtKinectDemo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.actionInformation.setFont(font)
        self.actionInformation.setObjectName("actionInformation")
        self.actionExit = QtWidgets.QAction(PyQtKinectDemo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.menuMain.addAction(self.actionInformation)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionExit)
        self.menuBar.addAction(self.menuMain.menuAction())

        self.retranslateUi(PyQtKinectDemo)
        QtCore.QMetaObject.connectSlotsByName(PyQtKinectDemo)

    def retranslateUi(self, PyQtKinectDemo):
        _translate = QtCore.QCoreApplication.translate
        PyQtKinectDemo.setWindowTitle(_translate("PyQtKinectDemo", "PyQt-Kinect Online Action Predictor"))
        self.uniLogoLabel.setText(_translate("PyQtKinectDemo", "(UQ logo)"))
        self.facultyLabel.setText(_translate("PyQtKinectDemo", "        Faculty of Engineering, Architecture and Infomation Technology"))
        self.schoolLabel.setText(_translate("PyQtKinectDemo", "        School of Information Technology and Electrical Engineering"))
        self.appTitleLabel.setText(_translate("PyQtKinectDemo", "Real-time Action Detector with Kinect & Neural Network"))
        self.label.setText(_translate("PyQtKinectDemo", "by Junhao Lin"))
        self.rgbTitle.setText(_translate("PyQtKinectDemo", "RGB Stream"))
        self.rgbLabel.setText(_translate("PyQtKinectDemo", "Not Available"))
        self.depthTitle.setText(_translate("PyQtKinectDemo", "Depth Stream"))
        self.depthLabel.setText(_translate("PyQtKinectDemo", "Not Available"))
        self.actionListTitleLabel.setText(_translate("PyQtKinectDemo", "List of Available Actions"))
        self.actionClassTitleLabel.setText(_translate("PyQtKinectDemo", "Action Class Prediction"))
        self.actionClassTitleLabel2.setText(_translate("PyQtKinectDemo", "Action Class Confidence"))
        self.actionEndTitleLabel.setText(_translate("PyQtKinectDemo", "Action End Confidence"))
        self.actionStartTitleLabel.setText(_translate("PyQtKinectDemo", "Action Start Confidence"))
        self.eventTitleLabel.setText(_translate("PyQtKinectDemo", "Event Prediction"))
        self.actionClassNameLabel.setText(_translate("PyQtKinectDemo", "Unknown"))
        self.actionClassConfidenceLabel.setText(_translate("PyQtKinectDemo", "0.00 %"))
        self.eventPredictLabel.setText(_translate("PyQtKinectDemo", "No Action"))
        self.actionStartConfidenceLabel.setText(_translate("PyQtKinectDemo", "0.00 %"))
        self.actionEndConfidenceLabel.setText(_translate("PyQtKinectDemo", "0.00 %"))
        self.instructionLabel.setText(_translate("PyQtKinectDemo", "<html><head/><body><p align=\"justify\"><span style=\" font-weight:600; font-style:italic;\">Instructions:</span><span style=\" font-style:italic;\"> Face the camera. Ensure that your skeleton is detected and mostly displayed on &quot;RGB stream&quot;, then hit &quot;Start&quot;! Try performing an action for longer time or multiple times if not detected. You might need to be idle for a few seconds after the action has been performed to allow the camera calibration. Actions not in &quot;List of Available Actions&quot; will not be detected correctly. Currently no more than two people can be in the scope.  Uncheck &quot;Enable Interaction Actions&quot; if available to detect only actions by one person. Tune &quot;Frame Rate Control&quot; to change how frequently the neural network is oberserving the skeleton movements.</span></p></body></html>"))
        self.predictSettingTitleLabel.setText(_translate("PyQtKinectDemo", "Prediction Control"))
        self.datasetComboBox.setItemText(0, _translate("PyQtKinectDemo", "JL"))
        self.datasetComboBox.setItemText(1, _translate("PyQtKinectDemo", "PKU-MMD-CS"))
        self.datasetComboBox.setItemText(2, _translate("PyQtKinectDemo", "G3D"))
        self.stopPredictButton.setText(_translate("PyQtKinectDemo", "Stop"))
        self.startPredictButton.setText(_translate("PyQtKinectDemo", "Start"))
        self.interactCheckBox.setText(_translate("PyQtKinectDemo", "Enable Interaction Actions"))
        self.datasetLabel.setText(_translate("PyQtKinectDemo", "Select Dataset"))
        self.frameRateLabel.setText(_translate("PyQtKinectDemo", "Frame Rate Control"))
        self.frameRateValueLabel.setText(_translate("PyQtKinectDemo", "30.00"))
        self.sensorControlLabel.setText(_translate("PyQtKinectDemo", "Sensor Control"))
        self.resumeButton.setText(_translate("PyQtKinectDemo", "Resume Stream"))
        self.pauseButton.setText(_translate("PyQtKinectDemo", "Pause Stream"))
        self.tiltUpButton.setText(_translate("PyQtKinectDemo", "Tilt Up"))
        self.tiltDownButton.setText(_translate("PyQtKinectDemo", "Tilt Down"))
        self.resetButton.setText(_translate("PyQtKinectDemo", "Reset"))
        self.menuMain.setTitle(_translate("PyQtKinectDemo", "Menu"))
        self.actionSettings.setText(_translate("PyQtKinectDemo", "Settings"))
        self.actionInformation.setText(_translate("PyQtKinectDemo", "About"))
        self.actionExit.setText(_translate("PyQtKinectDemo", "Exit"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyQtKinectDemo = QtWidgets.QMainWindow()
    ui = Ui_PyQtKinectDemo()
    ui.setupUi(PyQtKinectDemo)
    PyQtKinectDemo.show()
    sys.exit(app.exec_())
