# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/_datasetCollector.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyQtKinect(object):
    def setupUi(self, PyQtKinect):
        PyQtKinect.setObjectName("PyQtKinect")
        PyQtKinect.resize(1362, 1014)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PyQtKinect.sizePolicy().hasHeightForWidth())
        PyQtKinect.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(PyQtKinect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.streamFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.streamFrame.sizePolicy().hasHeightForWidth())
        self.streamFrame.setSizePolicy(sizePolicy)
        self.streamFrame.setMinimumSize(QtCore.QSize(642, 242))
        self.streamFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.streamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.streamFrame.setObjectName("streamFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.streamFrame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rgbWidget = QtWidgets.QWidget(self.streamFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbWidget.sizePolicy().hasHeightForWidth())
        self.rgbWidget.setSizePolicy(sizePolicy)
        self.rgbWidget.setObjectName("rgbWidget")
        self.verticalTopLayout = QtWidgets.QVBoxLayout(self.rgbWidget)
        self.verticalTopLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalTopLayout.setSpacing(6)
        self.verticalTopLayout.setObjectName("verticalTopLayout")
        self.rgbTitle = QtWidgets.QLabel(self.rgbWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbTitle.sizePolicy().hasHeightForWidth())
        self.rgbTitle.setSizePolicy(sizePolicy)
        self.rgbTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.rgbTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rgbTitle.setFont(font)
        self.rgbTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbTitle.setObjectName("rgbTitle")
        self.verticalTopLayout.addWidget(self.rgbTitle)
        self.rgbLabel = QtWidgets.QLabel(self.rgbWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbLabel.sizePolicy().hasHeightForWidth())
        self.rgbLabel.setSizePolicy(sizePolicy)
        self.rgbLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.rgbLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.rgbLabel.setFont(font)
        self.rgbLabel.setAutoFillBackground(True)
        self.rgbLabel.setScaledContents(True)
        self.rgbLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbLabel.setObjectName("rgbLabel")
        self.verticalTopLayout.addWidget(self.rgbLabel)
        self.horizontalLayout.addWidget(self.rgbWidget)
        self.depthWidget = QtWidgets.QWidget(self.streamFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthWidget.sizePolicy().hasHeightForWidth())
        self.depthWidget.setSizePolicy(sizePolicy)
        self.depthWidget.setObjectName("depthWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.depthWidget)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.depthTitle = QtWidgets.QLabel(self.depthWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthTitle.sizePolicy().hasHeightForWidth())
        self.depthTitle.setSizePolicy(sizePolicy)
        self.depthTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.depthTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.depthTitle.setFont(font)
        self.depthTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.depthTitle.setObjectName("depthTitle")
        self.verticalLayout_5.addWidget(self.depthTitle)
        self.depthLabel = QtWidgets.QLabel(self.depthWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthLabel.sizePolicy().hasHeightForWidth())
        self.depthLabel.setSizePolicy(sizePolicy)
        self.depthLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.depthLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.depthLabel.setFont(font)
        self.depthLabel.setAutoFillBackground(True)
        self.depthLabel.setScaledContents(True)
        self.depthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.depthLabel.setObjectName("depthLabel")
        self.verticalLayout_5.addWidget(self.depthLabel)
        self.horizontalLayout.addWidget(self.depthWidget)
        self.verticalLayout_9.addWidget(self.streamFrame)
        self.middleButtonFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleButtonFrame.sizePolicy().hasHeightForWidth())
        self.middleButtonFrame.setSizePolicy(sizePolicy)
        self.middleButtonFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.middleButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middleButtonFrame.setObjectName("middleButtonFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.middleButtonFrame)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sensorControlLabel = QtWidgets.QLabel(self.middleButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorControlLabel.sizePolicy().hasHeightForWidth())
        self.sensorControlLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.sensorControlLabel.setFont(font)
        self.sensorControlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sensorControlLabel.setObjectName("sensorControlLabel")
        self.verticalLayout_6.addWidget(self.sensorControlLabel)
        self.horizontalWidget = QtWidgets.QWidget(self.middleButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pauseButton = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pauseButton.setFont(font)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_2.addWidget(self.pauseButton)
        self.resumeButton = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.resumeButton.setFont(font)
        self.resumeButton.setObjectName("resumeButton")
        self.horizontalLayout_2.addWidget(self.resumeButton)
        self.tiltUpButton = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tiltUpButton.setFont(font)
        self.tiltUpButton.setObjectName("tiltUpButton")
        self.horizontalLayout_2.addWidget(self.tiltUpButton)
        self.tiltDownButton = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tiltDownButton.setFont(font)
        self.tiltDownButton.setObjectName("tiltDownButton")
        self.horizontalLayout_2.addWidget(self.tiltDownButton)
        self.resetButton = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.verticalLayout_6.addWidget(self.horizontalWidget)
        self.verticalLayout_9.addWidget(self.middleButtonFrame)
        self.dataCollectFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataCollectFrame.sizePolicy().hasHeightForWidth())
        self.dataCollectFrame.setSizePolicy(sizePolicy)
        self.dataCollectFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.dataCollectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataCollectFrame.setObjectName("dataCollectFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dataCollectFrame)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dataCollectLabel = QtWidgets.QLabel(self.dataCollectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataCollectLabel.sizePolicy().hasHeightForWidth())
        self.dataCollectLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataCollectLabel.setFont(font)
        self.dataCollectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataCollectLabel.setObjectName("dataCollectLabel")
        self.verticalLayout_2.addWidget(self.dataCollectLabel)
        self.pathWidget = QtWidgets.QWidget(self.dataCollectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathWidget.sizePolicy().hasHeightForWidth())
        self.pathWidget.setSizePolicy(sizePolicy)
        self.pathWidget.setObjectName("pathWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pathWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pathLabel = QtWidgets.QLabel(self.pathWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pathLabel.setFont(font)
        self.pathLabel.setObjectName("pathLabel")
        self.horizontalLayout_3.addWidget(self.pathLabel)
        self.pathLineEdit = QtWidgets.QLineEdit(self.pathWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pathLineEdit.setFont(font)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.horizontalLayout_3.addWidget(self.pathLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.pathWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_3.addWidget(self.browseButton)
        self.verticalLayout_2.addWidget(self.pathWidget)
        self.recordingFrame = QtWidgets.QFrame(self.dataCollectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordingFrame.sizePolicy().hasHeightForWidth())
        self.recordingFrame.setSizePolicy(sizePolicy)
        self.recordingFrame.setObjectName("recordingFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.recordingFrame)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.actionClassComboBox = QtWidgets.QComboBox(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.actionClassComboBox.setFont(font)
        self.actionClassComboBox.setObjectName("actionClassComboBox")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.actionClassComboBox.addItem("")
        self.gridLayout.addWidget(self.actionClassComboBox, 1, 0, 1, 1)
        self.ageClassLabel = QtWidgets.QLabel(self.recordingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ageClassLabel.sizePolicy().hasHeightForWidth())
        self.ageClassLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.ageClassLabel.setFont(font)
        self.ageClassLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ageClassLabel.setObjectName("ageClassLabel")
        self.gridLayout.addWidget(self.ageClassLabel, 0, 2, 1, 1)
        self.personClassLabel = QtWidgets.QLabel(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.personClassLabel.setFont(font)
        self.personClassLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.personClassLabel.setObjectName("personClassLabel")
        self.gridLayout.addWidget(self.personClassLabel, 0, 3, 1, 1)
        self.discardButton = QtWidgets.QPushButton(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.discardButton.setFont(font)
        self.discardButton.setObjectName("discardButton")
        self.gridLayout.addWidget(self.discardButton, 1, 6, 1, 1)
        self.stopRecordButton = QtWidgets.QPushButton(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.stopRecordButton.setFont(font)
        self.stopRecordButton.setObjectName("stopRecordButton")
        self.gridLayout.addWidget(self.stopRecordButton, 1, 5, 1, 1)
        self.actionClassLabel = QtWidgets.QLabel(self.recordingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionClassLabel.sizePolicy().hasHeightForWidth())
        self.actionClassLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.actionClassLabel.setFont(font)
        self.actionClassLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.actionClassLabel.setObjectName("actionClassLabel")
        self.gridLayout.addWidget(self.actionClassLabel, 0, 0, 1, 1)
        self.ageClassComboBox = QtWidgets.QComboBox(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ageClassComboBox.setFont(font)
        self.ageClassComboBox.setObjectName("ageClassComboBox")
        self.ageClassComboBox.addItem("")
        self.ageClassComboBox.addItem("")
        self.gridLayout.addWidget(self.ageClassComboBox, 1, 2, 1, 1)
        self.startRecordButton = QtWidgets.QPushButton(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.startRecordButton.setFont(font)
        self.startRecordButton.setObjectName("startRecordButton")
        self.gridLayout.addWidget(self.startRecordButton, 0, 5, 1, 1)
        self.personClassComboBox = QtWidgets.QComboBox(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.personClassComboBox.setFont(font)
        self.personClassComboBox.setObjectName("personClassComboBox")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.personClassComboBox.addItem("")
        self.gridLayout.addWidget(self.personClassComboBox, 1, 3, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.recordingFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 0, 6, 1, 1)
        self.genderClassLabel = QtWidgets.QLabel(self.recordingFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.genderClassLabel.setFont(font)
        self.genderClassLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.genderClassLabel.setObjectName("genderClassLabel")
        self.gridLayout.addWidget(self.genderClassLabel, 0, 4, 1, 1)
        self.genderClassComboBox = QtWidgets.QComboBox(self.recordingFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.genderClassComboBox.setFont(font)
        self.genderClassComboBox.setObjectName("genderClassComboBox")
        self.genderClassComboBox.addItem("")
        self.genderClassComboBox.addItem("")
        self.gridLayout.addWidget(self.genderClassComboBox, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.recordingFrame)
        self.verticalLayout_9.addWidget(self.dataCollectFrame)
        self.logFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logFrame.sizePolicy().hasHeightForWidth())
        self.logFrame.setSizePolicy(sizePolicy)
        self.logFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.logFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logFrame.setObjectName("logFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.logFrame)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.programLogLabel = QtWidgets.QLabel(self.logFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programLogLabel.sizePolicy().hasHeightForWidth())
        self.programLogLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.programLogLabel.setFont(font)
        self.programLogLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.programLogLabel.setObjectName("programLogLabel")
        self.verticalLayout_3.addWidget(self.programLogLabel)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.logFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.verticalLayout_9.addWidget(self.logFrame)
        PyQtKinect.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(PyQtKinect)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1362, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        PyQtKinect.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(PyQtKinect)
        self.mainToolBar.setObjectName("mainToolBar")
        PyQtKinect.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(PyQtKinect)
        self.statusBar.setObjectName("statusBar")
        PyQtKinect.setStatusBar(self.statusBar)
        self.actionSettings = QtWidgets.QAction(PyQtKinect)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.actionSettings.setFont(font)
        self.actionSettings.setObjectName("actionSettings")
        self.actionInformation = QtWidgets.QAction(PyQtKinect)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.actionInformation.setFont(font)
        self.actionInformation.setObjectName("actionInformation")
        self.actionExit = QtWidgets.QAction(PyQtKinect)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.menuMain.addAction(self.actionSettings)
        self.menuMain.addAction(self.actionInformation)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionExit)
        self.menuBar.addAction(self.menuMain.menuAction())

        self.retranslateUi(PyQtKinect)
        QtCore.QMetaObject.connectSlotsByName(PyQtKinect)

    def retranslateUi(self, PyQtKinect):
        _translate = QtCore.QCoreApplication.translate
        PyQtKinect.setWindowTitle(_translate("PyQtKinect", "PyQt-Kinect Dataset Collector"))
        self.rgbTitle.setText(_translate("PyQtKinect", "RGB Stream"))
        self.rgbLabel.setText(_translate("PyQtKinect", "Not Available"))
        self.depthTitle.setText(_translate("PyQtKinect", "Depth Stream"))
        self.depthLabel.setText(_translate("PyQtKinect", "Not Available"))
        self.sensorControlLabel.setText(_translate("PyQtKinect", "Sensor Control"))
        self.pauseButton.setText(_translate("PyQtKinect", "Pause Stream"))
        self.resumeButton.setText(_translate("PyQtKinect", "Resume Stream"))
        self.tiltUpButton.setText(_translate("PyQtKinect", "Tilt Up"))
        self.tiltDownButton.setText(_translate("PyQtKinect", "Tilt Down"))
        self.resetButton.setText(_translate("PyQtKinect", "Reset"))
        self.dataCollectLabel.setText(_translate("PyQtKinect", "Data Collection"))
        self.pathLabel.setText(_translate("PyQtKinect", "Save Path"))
        self.browseButton.setText(_translate("PyQtKinect", "Browse"))
        self.actionClassComboBox.setItemText(0, _translate("PyQtKinect", "Walk"))
        self.actionClassComboBox.setItemText(1, _translate("PyQtKinect", "Wave"))
        self.actionClassComboBox.setItemText(2, _translate("PyQtKinect", "Clap"))
        self.actionClassComboBox.setItemText(3, _translate("PyQtKinect", "Drink"))
        self.actionClassComboBox.setItemText(4, _translate("PyQtKinect", "Sit Down"))
        self.actionClassComboBox.setItemText(5, _translate("PyQtKinect", "Stand Up"))
        self.actionClassComboBox.setItemText(6, _translate("PyQtKinect", "Throw"))
        self.actionClassComboBox.setItemText(7, _translate("PyQtKinect", "Crouch"))
        self.actionClassComboBox.setItemText(8, _translate("PyQtKinect", "One-leg Balance"))
        self.actionClassComboBox.setItemText(9, _translate("PyQtKinect", "Jump"))
        self.ageClassLabel.setText(_translate("PyQtKinect", "Age Class"))
        self.personClassLabel.setText(_translate("PyQtKinect", "Identity Class"))
        self.discardButton.setText(_translate("PyQtKinect", "Discard"))
        self.stopRecordButton.setText(_translate("PyQtKinect", "Stop Recording"))
        self.actionClassLabel.setText(_translate("PyQtKinect", "Action Class"))
        self.ageClassComboBox.setItemText(0, _translate("PyQtKinect", "Young / Not retired"))
        self.ageClassComboBox.setItemText(1, _translate("PyQtKinect", "Old / Retired"))
        self.startRecordButton.setText(_translate("PyQtKinect", "Start Recording"))
        self.personClassComboBox.setItemText(0, _translate("PyQtKinect", "1"))
        self.personClassComboBox.setItemText(1, _translate("PyQtKinect", "2"))
        self.personClassComboBox.setItemText(2, _translate("PyQtKinect", "3"))
        self.personClassComboBox.setItemText(3, _translate("PyQtKinect", "4"))
        self.personClassComboBox.setItemText(4, _translate("PyQtKinect", "5"))
        self.personClassComboBox.setItemText(5, _translate("PyQtKinect", "6"))
        self.personClassComboBox.setItemText(6, _translate("PyQtKinect", "7"))
        self.personClassComboBox.setItemText(7, _translate("PyQtKinect", "8"))
        self.personClassComboBox.setItemText(8, _translate("PyQtKinect", "9"))
        self.personClassComboBox.setItemText(9, _translate("PyQtKinect", "10"))
        self.personClassComboBox.setItemText(10, _translate("PyQtKinect", "11"))
        self.personClassComboBox.setItemText(11, _translate("PyQtKinect", "12"))
        self.personClassComboBox.setItemText(12, _translate("PyQtKinect", "13"))
        self.personClassComboBox.setItemText(13, _translate("PyQtKinect", "14"))
        self.personClassComboBox.setItemText(14, _translate("PyQtKinect", "15"))
        self.personClassComboBox.setItemText(15, _translate("PyQtKinect", "16"))
        self.personClassComboBox.setItemText(16, _translate("PyQtKinect", "17"))
        self.personClassComboBox.setItemText(17, _translate("PyQtKinect", "18"))
        self.personClassComboBox.setItemText(18, _translate("PyQtKinect", "19"))
        self.personClassComboBox.setItemText(19, _translate("PyQtKinect", "20"))
        self.saveButton.setText(_translate("PyQtKinect", "Save"))
        self.genderClassLabel.setText(_translate("PyQtKinect", "Gender Class"))
        self.genderClassComboBox.setItemText(0, _translate("PyQtKinect", "Male"))
        self.genderClassComboBox.setItemText(1, _translate("PyQtKinect", "Female"))
        self.programLogLabel.setText(_translate("PyQtKinect", "Program Logs"))
        self.menuMain.setTitle(_translate("PyQtKinect", "Menu"))
        self.actionSettings.setText(_translate("PyQtKinect", "Settings"))
        self.actionInformation.setText(_translate("PyQtKinect", "About"))
        self.actionExit.setText(_translate("PyQtKinect", "Exit"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyQtKinect = QtWidgets.QMainWindow()
    ui = Ui_PyQtKinect()
    ui.setupUi(PyQtKinect)
    PyQtKinect.show()
    sys.exit(app.exec_())
